In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("G:\My Drive\PowerBI\Customer analysis\customer_shopping_behavior.csv")

In [5]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [22]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [24]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [25]:
# Create a column age_group
labels=['Young Adult','Adult','Middle-aged','Semior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [27]:
df[['age','age_group']].head()

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged

In [28]:
df['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [30]:
#create a column purchase_frequency_days
frequency_mapping={'Fortnightly':14,
                   'Weekly':7,
                   'Annually':365,
                   'Quarterly':90, 
                   'Bi-Weekly':14,
                   'Monthly':30,
                   'Every 3 Months':90
                  }
df['frequency_mapping_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [31]:
df[['frequency_of_purchases','frequency_mapping_days']].head(10)

  frequency_of_purchases  frequency_mapping_days
0            Fortnightly                      14
1            Fortnightly                      14
2                 Weekly                       7
3                 Weekly                       7
4               Annually                     365
5                 Weekly                       7
6              Quarterly                      90
7                 Weekly                       7
8               Annually                     365
9              Quarterly                      90

In [34]:
df[['discount_applied','promo_code_used']]

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [35]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [36]:
df=df.drop(columns='promo_code_used',axis=1)

In [38]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'frequency_mapping_days'],
      dtype='object')

In [39]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\gops3\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\gops3\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\gops3\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 249.0 kB/s eta 0:00:09
   ------- -------------------------------- 0.5/2.8 MB 249.0 kB/s eta 0:00:09
   ------- -------------------------------- 0.5/2.8 MB 249.0 kB/s eta 0:00:09
   ------- -------------------------------- 0.5/2.8 MB 249.0 kB/s eta 0:00:09
   ------- -------------------------------- 0.5/2.8 MB 249.0 kB/s eta 0:00:09
   ------- -------------------------------- 0.5/2.8 MB 249.0 kB/s eta 0:00:09
   ----------- ---------------------------- 0.8/2.8 MB 237.2 kB/s eta 0:00:09
   ----------- ---------------------------- 0.8/2.8 MB 237.2 kB/s eta 0:00:09
   ----------- ---------------------------- 0.8/2.8 MB 237.2 kB/s eta 0:00:09
   ----------- ---------------------------- 0.8/2.8 MB 237.2 kB/s eta 0:00:09
   ----------- ---------------------------- 0.8/2.8 MB 237.2 kB/s eta 0:00:09
   --------------- ------------------------ 1.0/2.8 MB 235.9 kB/s eta 0:00:08
   --------------- ------------------------ 1.0/2.8 MB 235.9 kB/s eta 0:00:08
   --------------- ------------------------ 1.0/2.8 MB 235.9 kB/s eta 0:00:08
   --------------- ------------------------ 1.0/2.8 MB 235.9 kB/s eta 0:00:08
   --------------- ------------------------ 1.0/2.8 MB 235.9 kB/s eta 0:00:08
   --------------- ------------------------ 1.0/2.8 MB 235.9 kB/s eta 0:00:08
   --------------- ------------------------ 1.0/2.8 MB 235.9 kB/s eta 0:00:08
   --------------- ------------------------ 1.0/2.8 MB 235.9 kB/s eta 0:00:08
   --------------- ------------------------ 1.0/2.8 MB 235.9 kB/s eta 0:00:08
   --------------- ------------------------ 1.0/2.8 MB 235.9 kB/s eta 0:00:08
   --------------- ------------------------ 1.0/2.8 MB 235.9 kB/s eta 0:00:08
   --------------- ------------------------ 1.0/2.8 MB 235.9 kB/s eta 0:00:08
   --------------- ------------------------ 1.0/2.8 MB 235.9 kB/s eta 0:00:08
   --------------- ------------------------ 1.0/2.8 MB 235.9 kB/s eta 0:00:08
   --------------- ------------------------ 1.0/2.8 MB 235.9 kB/s eta 0:00:08
   ------------------- -------------------- 1.3/2.8 MB 160.5 kB/s eta 0:00:10
   ------------------- -------------------- 1.3/2.8 MB 160.5 kB/s eta 0:00:10
   ------------------- -------------------- 1.3/2.8 MB 160.5 kB/s eta 0:00:10
   ------------------- -------------------- 1.3/2.8 MB 160.5 kB/s eta 0:00:10
   ------------------- -------------------- 1.3/2.8 MB 160.5 kB/s eta 0:00:10
   ------------------- -------------------- 1.3/2.8 MB 160.5 kB/s eta 0:00:10
   ---------------------- ----------------- 1.6/2.8 MB 171.8 kB/s eta 0:00:07
   ---------------------- ----------------- 1.6/2.8 MB 171.8 kB/s eta 0:00:07
   ---------------------- ----------------- 1.6/2.8 MB 171.8 kB/s eta 0:00:07
   ---------------------- ----------------- 1.6/2.8 MB 171.8 kB/s eta 0:00:07
   -------------------------- ------------- 1.8/2.8 MB 186.2 kB/s eta 0:00:05
   -------------------------- ------------- 1.8/2.8 MB 186.2 kB/s eta 0:00:05
   -------------------------- ------------- 1.8/2.8 MB 186.2 kB/s eta 0:00:05
   -------------------------- ------------- 1.8/2.8 MB 186.2 kB/s eta 0:00:05
   -------------------------- ------------- 1.8/2.8 MB 186.2 kB/s eta 0:00:05
   -------------------------- ------------- 1.8/2.8 MB 186.2 kB/s eta 0:00:05
   ------------------------------ --------- 2.1/2.8 MB 185.5 kB/s eta 0:00:04
   ------------------------------ --------- 2.1/2.8 MB 185.5 kB/s eta 0:00:04
   ------------------------------ --------- 2.1/2.8 MB 185.5 kB/s eta 0:00:04
   ------------------------------ --------- 2.1/2.8 MB 185.5 kB/s eta 0:00:04
   ---------------------------------- ----- 2.4/2.8 MB 196.9 kB/s eta 0:00:03
   ---------------------------------- ----- 2.4/2.8 MB 196.9 kB/s eta 0:00:03
   -------------------------------------- - 2.6/2.8 MB 213.1 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.8 MB 213.1 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.8 MB 213.1 kB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 214.6 kB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [40]:
pip install pyodbc pandas sqlalchemy

Requirement already satisfied: pyodbc in c:\users\gops3\anaconda3\lib\site-packages (5.2.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pandas in c:\users\gops3\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: sqlalchemy in c:\users\gops3\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: numpy>=1.26.0 in c:\users\gops3\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gops3\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\gops3\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\gops3\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\gops3\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\gops3\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: six>=1.5 in c:\users\gops3\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [42]:
import pyodbc

conn = pyodbc.connect(
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=Jalps\MSSQL;'
    'DATABASE=customerDB;'
    'Trusted_Connection=yes;'
)

cursor = conn.cursor()

print("Connected Successfully")

Connected Successfully

In [ ]:
# SQLAlchemy connection string
engine = create_engine(
    "mssql+pyodbc://USERNAME:PASSWORD@SERVERNAME/DATABASENAME?driver=ODBC+Driver+17+for+SQL+Server"
)

# Load DataFrame into SQL table
df.to_sql("Employees", con=engine, if_exists="append", index=False)

In [44]:
from sqlalchemy import create_engine
engine = create_engine(
    "mssql+pyodbc://Jalps\MSSQL/customerDB?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

df.to_sql(
    "Employee",
    engine,
    if_exists="append",
    index=False
)

print("Data Loaded Successfully")

Data Loaded Successfully